// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdlsckvtkevpdpafhgpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkbHNja3Z0a2V2cGRwYWZoZ3BkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzY3ODMsImV4cCI6MjA3MTAxMjc4M30.KGwNdH0PVYsp_6RIp-bNeB5mD2HlgNuscBOGT_IlqFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});